/**
 * Multi-Language Default Sample Data
 * Provides localized default demo records for:
 * 1. Notes
 * 2. Reminders / Tasks
 * 3. Medicines
 * 4. Finance & Transactions
 * 5. Khata (Debits & Credits)
 * 6. Special Events (Birthdays & Anniversaries)
 * Supported languages: gu, hi, en, es, fr, de, ar
 */

export const getDefaultNotes = (lang = 'gu') => {
  const todayStr = new Date().toISOString().split('T')[0];

  const notesByLang = {
    gu: [
      {
        id: 'note-1',
        title: 'આજના અગત્યના વિચારો અને લક્ષ્ય',
        content: 'રોજબરોજના જીવનમાં સમયનું યોગ્ય આયોજન કરવું જરૂરી છે. આજે બેંકનું કામ અને ઓફિસની નવી ફાઇલ પૂરી કરવાની છે.',
        category: 'અંગત',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'ઘર માટે લાવવાની વસ્તુઓ (કરિયાણું)',
        content: '૧. ઘઉંનો લોટ ૫ કિલો\n૨. તેલ ૧ ડબ્બો\n૩. દાળ અને મસાલા\n૪. નાસ્તો',
        category: 'કામ',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    hi: [
      {
        id: 'note-1',
        title: 'आज के महत्वपूर्ण विचार और लक्ष्य',
        content: 'दैनिक जीवन में समय का सही प्रबंधन आवश्यक है। आज बैंक का काम और कार्यालय की नई फाइल पूरी करनी है।',
        category: 'व्यक्तिगत',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'घर के लिए आवश्यक सामान (किराना)',
        content: '१. गेहूं का आटा ५ किलो\n२. तेल १ डिब्बा\n३. दाल और मसाले\n४. नाश्ता',
        category: 'कार्य',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    en: [
      {
        id: 'note-1',
        title: "Today's Important Thoughts & Goals",
        content: 'Proper time management is essential in daily life. Complete the bank tasks and new office files today.',
        category: 'Personal',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'Home Grocery Shopping List',
        content: '1. Whole wheat flour 5 kg\n2. Cooking oil 1 container\n3. Pulses and spices\n4. Healthy snacks',
        category: 'Work',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    es: [
      {
        id: 'note-1',
        title: 'Pensamientos y Objetivos de Hoy',
        content: 'La gestión del tiempo es esencial en la vida diaria. Terminar los trámites bancarios y los nuevos archivos de oficina hoy.',
        category: 'Personal',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'Lista de Compras del Hogar',
        content: '1. Harina de trigo 5 kg\n2. Aceite de cocina 1 litro\n3. Legumbres y especias\n4. Aperitivos saludables',
        category: 'Trabajo',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    fr: [
      {
        id: 'note-1',
        title: "Pensées et Objectifs d'Aujourd'hui",
        content: 'La gestion du temps est essentielle au quotidien. Terminer les démarches bancaires et les nouveaux dossiers aujourd’hui.',
        category: 'Personnel',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'Liste de Courses pour la Maison',
        content: '1. Farine de blé 5 kg\n2. Huile de cuisson 1 boîte\n3. Légumes secs et épices\n4. Collations saines',
        category: 'Travail',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    de: [
      {
        id: 'note-1',
        title: 'Heutige Gedanken und Ziele',
        content: 'Zeitmanagement ist im Alltag unerlässlich. Heute die Bankgeschäfte und die neuen Büroakten abschließen.',
        category: 'Persönlich',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'Einkaufsliste für Zuhause',
        content: '1. Weizenmehl 5 kg\n2. Speiseöl 1 Dose\n3. Hülsenfrüchte & Gewürze\n4. Gesunde Snacks',
        category: 'Arbeit',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
    ar: [
      {
        id: 'note-1',
        title: 'أفكار وأهداف اليوم الهامة',
        content: 'إدارة الوقت أمر أساسي في الحياة اليومية. إنجاز أعمال البنك والملفات المكتبية الجديدة اليوم.',
        category: 'شخصي',
        date: todayStr,
        isPinned: true,
        color: '#eff6ff',
      },
      {
        id: 'note-2',
        title: 'قائمة مشتريات البقالة للمنزل',
        content: '١. دقيق قمح ٥ كجم\n٢. زيت طهي عبوة واحدة\n٣. بقوليات وتوابل\n٤. وجبات خفيفة صحية',
        category: 'العمل',
        date: todayStr,
        isPinned: false,
        color: '#f0fdf4',
      },
    ],
  };

  return notesByLang[lang] || notesByLang.en || notesByLang.gu;
};

export const getDefaultReminders = (lang = 'gu') => {
  const todayStr = new Date().toISOString().split('T')[0];

  const remindersByLang = {
    gu: [
      {
        id: 'rem-1',
        title: 'બેંક ઓફ બરોડા - ચેક જમા કરાવવો',
        description: 'નવી ચેકબુકની એન્ટ્રી કરાવવી અને ગ્રાન્ટનો ચેક ક્લિયરન્સમાં નાખવો.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'પ્રોજેક્ટ ટીમ સાથે મીટિંગ',
        description: 'નવી ડાયરી એપના રીવ્યુ અને ફીડબેક માટે ઝૂમ મીટિંગ.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'લાઈટ બિલ અને મોબાઈલ રિચાર્જ',
        description: 'ઓનલાઈન UPI દ્વારા બિલ ચૂકવી દેવું જેથી પેનલ્ટી ન લાગે.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    hi: [
      {
        id: 'rem-1',
        title: 'बैंक ऑफ बड़ौदा - चेक जमा करना',
        description: 'नई चेकबुक की एंट्री करवाना और ग्रांट का चेक क्लीयरेंस में डालना।',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'प्रोजेक्ट टीम के साथ मीटिंग',
        description: 'नई डायरी ऐप की समीक्षा और फीडबैक के लिए ज़ूम मीटिंग।',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'बिजली बिल और मोबाइल रिचार्ज',
        description: 'ऑनलाइन यूपीआई द्वारा बिल का भुगतान करना ताकि पेनल्टी न लगे।',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    en: [
      {
        id: 'rem-1',
        title: 'Bank of Baroda - Cheque Deposit',
        description: 'Submit new chequebook request and deposit grant cheque for clearance.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'Project Team Review Meeting',
        description: 'Zoom meeting for review and feedback on the new daily diary app.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'Electricity Bill & Mobile Recharge',
        description: 'Pay utility bills online via UPI before due date to avoid penalty.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    es: [
      {
        id: 'rem-1',
        title: 'Banco - Depósito de Cheque',
        description: 'Solicitar nueva chequera y depositar el cheque para compensación.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'Reunión con el Equipo del Proyecto',
        description: 'Reunión en Zoom para revisión y comentarios de la nueva aplicación.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'Factura de Luz y Recarga Móvil',
        description: 'Pagar facturas en línea antes de la fecha límite para evitar recargos.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    fr: [
      {
        id: 'rem-1',
        title: 'Banque - Dépôt de Chèque',
        description: 'Demander un nouveau chéquier et déposer le chèque pour encaissement.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: "Réunion d'Équipe Projet",
        description: 'Réunion Zoom pour la révision et les retours sur la nouvelle application.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: "Facture d'Électricité & Recharge Mobile",
        description: 'Payer les factures en ligne avant la date limite pour éviter les pénalités.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    de: [
      {
        id: 'rem-1',
        title: 'Bank - Scheck einreichen',
        description: 'Neues Scheckheft beantragen und Förderscheck zur Verrechnung einreichen.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'Projekt-Team-Meeting',
        description: 'Zoom-Meeting zur Überprüfung und Rückmeldung der neuen Tagebuch-App.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'Stromrechnung & Handy-Aufladung',
        description: 'Rechnungen online über UPI fristgerecht bezahlen.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
    ar: [
      {
        id: 'rem-1',
        title: 'البنك - إيداع الشيك',
        description: 'طلب دفتر شيكات جديد وإيداع الشيك للتحصيل.',
        type: 'bank',
        time: '11:00',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'high',
      },
      {
        id: 'rem-2',
        title: 'اجتماع مع فريق المشروع',
        description: 'اجتماع عبر زووم لمراجعة التطبيق الجديد وتلقي الملاحظات.',
        type: 'meeting',
        time: '15:30',
        date: todayStr,
        hasAlarm: true,
        isCompleted: false,
        priority: 'medium',
      },
      {
        id: 'rem-3',
        title: 'فاتورة الكهرباء وشحن رصيد الهاتف',
        description: 'سداد الفواتير عبر الإنترنت قبل موعد الاستحقاق لتجنب الغرامات.',
        type: 'task',
        time: '18:00',
        date: todayStr,
        hasAlarm: false,
        isCompleted: true,
        priority: 'normal',
      },
    ],
  };

  return remindersByLang[lang] || remindersByLang.en || remindersByLang.gu;
};

export const getDefaultMedicines = (lang = 'gu') => {
  const medsByLang = {
    gu: [
      {
        id: 'med-1',
        name: 'પેન્ટોપ્રાઝોલ (Pantocid 40)',
        dosage: '૧ ગોળી',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'સવારે ઉઠીને ખાલી પેટે નવશેકા પાણી સાથે લેવી.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'ડાયાબિટીસ ગોળી (Metformin 500)',
        dosage: '૧ ગોળી',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'સવારના નાસ્તા પછી તરત લેવી.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'મલ્ટીવિટામિન / કેલ્શિયમ',
        dosage: '૧ ગોળી',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'બપોરે ભોજન લીધા પછી લેવી.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'બીપીની દવા (Telmisartan 40)',
        dosage: '૧ ગોળી',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'રાત્રે જમીને સૂતા પહેલાં નિયમિત લેવી.',
        hasAlarm: true,
        active: true,
      },
    ],
    hi: [
      {
        id: 'med-1',
        name: 'पेंटोप्राजोल (Pantocid 40)',
        dosage: '१ गोली',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'सुबह उठकर खाली पेट गुनगुने पानी के साथ लें।',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'डायबिटीज दवा (Metformin 500)',
        dosage: '१ गोली',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'सुबह के नाश्ते के बाद तुरंत लें।',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'मल्टीविटामिन / कैल्शियम',
        dosage: '१ गोली',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'दोपहर के भोजन के बाद लें।',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'बीपी की दवा (Telmisartan 40)',
        dosage: '१ गोली',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'रात को खाने के बाद सोने से पहले नियमित लें।',
        hasAlarm: true,
        active: true,
      },
    ],
    en: [
      {
        id: 'med-1',
        name: 'Pantoprazole (Pantocid 40)',
        dosage: '1 Tablet',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'Take on empty stomach with warm water in the morning.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'Diabetes Tablet (Metformin 500)',
        dosage: '1 Tablet',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'Take immediately after morning breakfast.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'Multivitamin / Calcium',
        dosage: '1 Tablet',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'Take after lunch in the afternoon.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'Blood Pressure (Telmisartan 40)',
        dosage: '1 Tablet',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'Take regularly at night after dinner before sleeping.',
        hasAlarm: true,
        active: true,
      },
    ],
    es: [
      {
        id: 'med-1',
        name: 'Pantoprazol (Pantocid 40)',
        dosage: '1 Tableta',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'Tomar en ayunas con agua tibia por la mañana.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'Medicamento Diabetes (Metformina 500)',
        dosage: '1 Tableta',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'Tomar inmediatamente después del desayuno.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'Multivitamínico / Calcio',
        dosage: '1 Tableta',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'Tomar después del almuerzo.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'Presión Arterial (Telmisartán 40)',
        dosage: '1 Tableta',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'Tomar por la noche después de cenar.',
        hasAlarm: true,
        active: true,
      },
    ],
    fr: [
      {
        id: 'med-1',
        name: 'Pantoprazole (Pantocid 40)',
        dosage: '1 Comprimé',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'Prendre à jeun le matin avec de l’eau tiède.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'Diabète (Metformine 500)',
        dosage: '1 Comprimé',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'Prendre juste après le petit-déjeuner.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'Multivitamines / Calcium',
        dosage: '1 Comprimé',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'Prendre après le déjeuner.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'Tension Artérielle (Telmisartan 40)',
        dosage: '1 Comprimé',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'Prendre le soir après le dîner.',
        hasAlarm: true,
        active: true,
      },
    ],
    de: [
      {
        id: 'med-1',
        name: 'Pantoprazol (Pantocid 40)',
        dosage: '1 Tablette',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'Morgens nüchtern mit lauwarmem Wasser einnehmen.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'Diabetes (Metformin 500)',
        dosage: '1 Tablette',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'Direkt nach dem Frühstück einnehmen.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'Multivitamin / Calcium',
        dosage: '1 Tablette',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'Nach dem Mittagessen einnehmen.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'Blutdruck (Telmisartan 40)',
        dosage: '1 Tablette',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'Abends vor dem Schlafen regelmäßig einnehmen.',
        hasAlarm: true,
        active: true,
      },
    ],
    ar: [
      {
        id: 'med-1',
        name: 'بانتوبرازول (Pantocid 40)',
        dosage: 'قرص واحد',
        timeSlot: 'morning',
        mealRelation: 'before_food',
        time: '07:30',
        notes: 'يؤخذ صباحاً على الريق مع ماء فاتر.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-2',
        name: 'دواء السكري (Metformin 500)',
        dosage: 'قرص واحد',
        timeSlot: 'morning',
        mealRelation: 'after_food',
        time: '08:45',
        notes: 'يؤخذ مباشرة بعد وجبة الإفطار.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-3',
        name: 'فيتامينات متعددة / كالسيوم',
        dosage: 'قرص واحد',
        timeSlot: 'afternoon',
        mealRelation: 'after_food',
        time: '13:30',
        notes: 'يؤخذ بعد وجبة الغداء.',
        hasAlarm: true,
        active: true,
      },
      {
        id: 'med-4',
        name: 'دواء ضغط الدم (Telmisartan 40)',
        dosage: 'قرص واحد',
        timeSlot: 'night',
        mealRelation: 'after_food',
        time: '21:00',
        notes: 'يؤخذ بانتظام ليلاً بعد العشاء قبل النوم.',
        hasAlarm: true,
        active: true,
      },
    ],
  };

  return medsByLang[lang] || medsByLang.en || medsByLang.gu;
};

export const getDefaultFinance = (lang = 'gu') => {
  const todayStr = new Date().toISOString().split('T')[0];

  const categories = {
    gu: { salary: 'પગાર / આવક', grocery: 'કરિયાણું / ઘરખર્ચ', medicine: 'દવાઓ / હેલ્થ', fuel: 'પેટ્રોલ / મુસાફરી' },
    hi: { salary: 'वेतन / आय', grocery: 'किराना / घरेलू खर्च', medicine: 'दवा / स्वास्थ्य', fuel: 'पेट्रोल / यात्रा' },
    en: { salary: 'Salary / Income', grocery: 'Groceries / Household', medicine: 'Medicine / Health', fuel: 'Fuel / Travel' },
    es: { salary: 'Salario / Ingresos', grocery: 'Comestibles / Hogar', medicine: 'Medicina / Salud', fuel: 'Combustible / Viaje' },
    fr: { salary: 'Salaire / Revenus', grocery: 'Épicerie / Maison', medicine: 'Médicaments / Santé', fuel: 'Carburant / Déplacement' },
    de: { salary: 'Gehalt / Einkommen', grocery: 'Lebensmittel / Haushalt', medicine: 'Medizin / Gesundheit', fuel: 'Kraftstoff / Reise' },
    ar: { salary: 'راتب / دخل', grocery: 'بقالة / مستلزمات المنزل', medicine: 'أدوية / صحة', fuel: 'وقود / سفر' },
  };

  const descriptions = {
    gu: {
      sal: 'માસિક પગાર ખાતામાં જમા થયો',
      groc: 'ડી-માર્ટ કરિયાણું અને શાકભાજી',
      med: 'મેડિકલ સ્ટોરમાંથી મહિનાની દવાઓ',
      pet: 'ગાડીમાં પેટ્રોલ પુરાવ્યું',
    },
    hi: {
      sal: 'मासिक वेतन खाते में जमा हुआ',
      groc: 'डी-मार्ट किराना और सब्जियां',
      med: 'मेडिकल स्टोर से महीने की दवाइयाँ',
      pet: 'गाड़ी में पेट्रोल भरवाया',
    },
    en: {
      sal: 'Monthly salary credited to bank account',
      groc: 'Supermarket groceries and fresh vegetables',
      med: 'Monthly prescribed medicines from pharmacy',
      pet: 'Vehicle fuel refill',
    },
    es: {
      sal: 'Salario mensual acreditado en cuenta',
      groc: 'Supermercado comestibles y verduras frescas',
      med: 'Medicamentos recetados de la farmacia',
      pet: 'Recarga de combustible para el vehículo',
    },
    fr: {
      sal: 'Salaire mensuel crédité sur le compte',
      groc: 'Épicerie et légumes frais au supermarché',
      med: 'Médicaments du mois à la pharmacie',
      pet: 'Plein de carburant du véhicule',
    },
    de: {
      sal: 'Monatsgehalt auf Bankkonto gutgeschrieben',
      groc: 'Supermarkt Lebensmittel und frisches Gemüse',
      med: 'Monatliche Medikamente aus der Apotheke',
      pet: 'Fahrzeugbetankung',
    },
    ar: {
      sal: 'تم إيداع الراتب الشهري في الحساب البنكي',
      groc: 'شراء بقالة وخضراوات طازجة من السوبرماركت',
      med: 'أدوية الشهر من الصيدلية',
      pet: 'تعبئة وقود السيارة',
    },
  };

  const cat = categories[lang] || categories.en || categories.gu;
  const desc = descriptions[lang] || descriptions.en || descriptions.gu;

  return [
    {
      id: 'fin-1',
      type: 'income',
      amount: 45000,
      category: cat.salary,
      description: desc.sal,
      date: todayStr,
      paymentMode: 'Bank Transfer',
    },
    {
      id: 'fin-2',
      type: 'expense',
      amount: 2850,
      category: cat.grocery,
      description: desc.groc,
      date: todayStr,
      paymentMode: 'UPI',
    },
    {
      id: 'fin-3',
      type: 'expense',
      amount: 750,
      category: cat.medicine,
      description: desc.med,
      date: todayStr,
      paymentMode: 'Cash',
    },
    {
      id: 'fin-4',
      type: 'expense',
      amount: 500,
      category: cat.fuel,
      description: desc.pet,
      date: todayStr,
      paymentMode: 'UPI',
    },
  ];
};

export const getDefaultKhata = (lang = 'gu') => {
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  const due1 = new Date(today.getTime() + 7 * 86400000).toISOString().split('T')[0];
  const due2 = new Date(today.getTime() + 5 * 86400000).toISOString().split('T')[0];

  const descByLang = {
    gu: { kh1: 'દુકાનના માલના બાકી નાણાં', kh2: 'કાચા માલ ખરીદીનું પેમેન્ટ' },
    hi: { kh1: 'दुकान के सामान का बकाया भुगतान', kh2: 'कच्चे माल की खरीद का भुगतान' },
    en: { kh1: 'Pending balance for shop merchandise', kh2: 'Payment for raw materials purchase' },
    es: { kh1: 'Saldo pendiente por mercancía de la tienda', kh2: 'Pago por compra de materias primas' },
    fr: { kh1: 'Solde en attente pour marchandises', kh2: 'Paiement pour achat de matières premières' },
    de: { kh1: 'Ausstehender Betrag für Ladenwaren', kh2: 'Zahlung für Rohstoffeinkauf' },
    ar: { kh1: 'مستحقات متبقية عن بضائع المحل', kh2: 'سداد ثمن شراء المواد الخام' },
  };

  const d = descByLang[lang] || descByLang.en || descByLang.gu;

  return [
    {
      id: 'kh-1',
      partyName: 'રમેશભાઈ શાહ (Ramesh Shah)',
      phone: '9825011223',
      type: 'to_receive',
      amount: 5000,
      date: todayStr,
      dueDate: due1,
      description: d.kh1,
      isSettled: false,
    },
    {
      id: 'kh-2',
      partyName: 'કૃષ્ણ ટ્રેડર્સ (Krishna Traders)',
      phone: '9428044556',
      type: 'to_pay',
      amount: 3200,
      date: todayStr,
      dueDate: due2,
      description: d.kh2,
      isSettled: false,
    },
  ];
};

export const getDefaultEvents = (lang = 'gu') => {
  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];
  const tomorrowStr = new Date(today.getTime() + 86400000).toISOString().split('T')[0];

  const dataByLang = {
    gu: {
      rel1: 'મિત્ર (Friend)',
      notes1: 'સાંજે ૭ વાગે જન્મદિવસ પાર્ટી',
      rel2: 'કાકા-કાકી',
      notes2: 'લગ્ન વર્ષગાંઠ (૨૫મી સિલ્વર જ્યુબિલી)',
    },
    hi: {
      rel1: 'मित्र (Friend)',
      notes1: 'शाम को 7 बजे जन्मदिन की पार्टी',
      rel2: 'चाचा-चाची',
      notes2: 'शादी की सालगिरह (25वीं सिल्वर जुबली)',
    },
    en: {
      rel1: 'Friend',
      notes1: 'Birthday celebration party at 7 PM',
      rel2: 'Uncle & Aunt',
      notes2: 'Wedding Anniversary (25th Silver Jubilee)',
    },
    es: {
      rel1: 'Amigo',
      notes1: 'Fiesta de cumpleaños a las 19:00',
      rel2: 'Tíos',
      notes2: 'Aniversario de bodas (Bodas de plata)',
    },
    fr: {
      rel1: 'Ami',
      notes1: "Fête d'anniversaire à 19h00",
      rel2: 'Oncle & Tante',
      notes2: 'Anniversaire de mariage (Noces d’argent)',
    },
    de: {
      rel1: 'Freund',
      notes1: 'Geburtstagsparty um 19:00 Uhr',
      rel2: 'Onkel & Tante',
      notes2: 'Hochzeitstag (25. Silberne Hochzeit)',
    },
    ar: {
      rel1: 'صديق',
      notes1: 'حفلة عيد الميلاد في الساعة ٧ مساءً',
      rel2: 'العم والعمة',
      notes2: 'ذكرى الزواج (اليوبيل الفضي الـ ٢٥)',
    },
  };

  const d = dataByLang[lang] || dataByLang.en || dataByLang.gu;

  return [
    {
      id: 'ev-1',
      name: 'રમેશભાઈ શાહ (Ramesh Shah)',
      type: 'birthday',
      date: todayStr,
      phone: '9825011223',
      relation: d.rel1,
      notes: d.notes1,
    },
    {
      id: 'ev-2',
      name: 'મુકેશભાઈ & રીતાબેન (Mukesh & Rita)',
      type: 'anniversary',
      date: tomorrowStr,
      phone: '9428044556',
      relation: d.rel2,
      notes: d.notes2,
    },
  ];
};
